# --- PERFORMANS AYARLARI ---
min_particles: 500
max_particles: 2000
kld_err: 0.05
kld_z: 0.99
update_min_d: 0.1
update_min_a: 0.1
resample_interval: 2
transform_tolerance: 3.0    # Gecikme toleransı
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0
gui_publish_rate: 1.0

# --- SENSÖR AYARLARI ---
laser_max_beams: 30
laser_z_hit: 0.95
laser_z_short: 0.1
laser_z_max: 0.05
laser_z_rand: 0.05
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_model_type: "likelihood_field"
laser_likelihood_max_dist: 2.0

# --- FRAME AYARLARI ---
odom_model_type: "diff"
odom_alpha1: 0.1
odom_alpha2: 0.1
odom_alpha3: 0.1
odom_alpha4: 0.1
odom_frame_id: "odom"
base_frame_id: "base_footprint"
global_frame_id: "map"
tf_broadcast: true

