obstacle_range: 2.0
raytrace_range: 2.5

footprint: [[0.17, 0.17], [0.17, -0.17], [-0.17, -0.17], [-0.17, 0.17]]

inflation_radius: 0.15
cost_scaling_factor: 5.0

observation_sources: scan
scan:
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true

